#!/bin/bash

if [ $#  -lt 2 ]; then
    echo "Usages: ./hi train|chart|test|valid|detect tag [step]"
fi

Step="final"

if [ -d "$3" ]; then
    DataDir="$3"
elif [ -n "$3" ]; then
    Step="$3"
fi

Tag=$2
Root="/home/Aa"
BinDir="$Root/remote/yolo/darknet"
DataDir=${DataDir:-"$Root/remote/data"}
BackUpDir="$DataDir/${Tag}/backup"
BackUpFile="${BackUpDir}/${Tag}/backup"
Weights="${BackUpDir}/${Tag}_${Step}.weights"
LogDir="$DataDir/$Tag/log"
Log="${LogDir}/train.log"
TrainData=$DataDir"/"$Tag"/"$Tag".data"
TrainCfg=$DataDir"/"$Tag"/"$Tag".cfg"
ScriptsDir="$Root/remote/scripts"

Cnf="${DataDir}/${Tag}/conf.ini"

GPUs=$(grep gpus $Cnf | awk -F '=' '{print $2}')
GPUs=${GPUs:-"0"}

Thresh=$(grep thresh $Cnf | awk -F '=' '{print $2}')
Thresh=${Thresh:-"0.25"}


PredictionsDir=$(grep predictions $Cnf | awk -F '=' '{print $2}')
PredictionsDir=${PredictionsDir:-"/home/Aa/data/$Tag/predictions"}

mkdir -p "$LogDir"
mkdir -p "$BackUpDir"
mkdir -p $PredictionsDir

cd $BinDir

case $1 in
    "train")
        batch=$(grep batch $Cnf | awk -F '=' '{print $2}')
        subdivisions=$(grep subdivisions $Cnf | awk -F '=' '{print $2}')
        width=$(grep width $Cnf | awk -F '=' '{print $2}')
        height=$(grep height $Cnf | awk -F '=' '{print $2}')
        if [ -n "$batch" ]; then
            sed -i "s/^\s*batch\s*=.*$/batch=$batch/g" ${TrainCfg}
        fi
        if [ -n "$subdivisions" ]; then
            sed -i "s/^\s*subdivisions\s*=.*$/subdivisions=$subdivisions/g" ${TrainCfg}
        fi
        if [ -n "$width" ]; then
            sed -i "s/^\s*width\s*=.*$/width=$width/g" ${TrainCfg}
        fi
        if [ -n "$height" ]; then
            sed -i "s/^\s*height\s*=.*$/height=$height/g" ${TrainCfg}
        fi

        if [ -f "$BackUpFile" ]; then
            echo "${BinDir}/darknet detector train ${TrainData} ${TrainCfg} ${BackUpFile} -gpus $GPUs >> ${Log} 2>&1 &"
            ${BinDir}/darknet detector train ${TrainData} ${TrainCfg} ${BackUpFile} -gpus $GPUs >> ${Log} 2>&1 &
        else 
            rm -f $Log
            echo "${BinDir}/darknet detector train ${TrainData} ${TrainCfg} ${BinDir}/darknet53.conv.74 -gpus $GPUs >> ${Log} 2>&1 &"
            ${BinDir}/darknet detector train ${TrainData} ${TrainCfg} ${BinDir}/darknet53.conv.74 -gpus $GPUs >> ${Log} 2>&1 &
        fi

        echo "Batch: ${batch}, Subdivisions: ${subdivisions}, Height ${height}, Width ${width}"
        watch nvidia-smi
    ;;
    "chart")
        python3 ${ScriptsDir}/extract_log.py $Log
        sed -i "/Saving/d" $Log".iou"
        sed -i "/Saving/d" $Log".loss"
        python ${ScriptsDir}/train_iou_visualization.py $Log".iou"
        python ${ScriptsDir}/train_loss_visualization.py $Log".loss"
        rm -f $Log".iou"
        rm -f $Log".loss"
    ;;
    "valid"|"test"|"detect")
        sed -i 's/^\s*batch\s*=.*$/batch=1/g' ${TrainCfg}
        sed -i 's/^\s*subdivisions\s*=.*$/subdivisions=1/g' ${TrainCfg}
        validFile=$(grep "valid" $TrainData | awk -F '=' '{print $2}')

        echo "${BinDir}/darknet detector test ${TrainData} ${TrainCfg} $Weights $validFile -gpus 0 -thresh $Thresh -out $PredictionsDir"
        ${BinDir}/darknet detector test ${TrainData} ${TrainCfg} $Weights $validFile -gpus 0 -thresh $Thresh -out $PredictionsDir

        # while read img
        # do
        #     fn=${img##*/}
        #     out=$PredictionsDir"/"$fn
        #     ${BinDir}/darknet detector test ${TrainData} ${TrainCfg} $Weights $img -gpus 0 -thresh $Thresh -out $out
        #     echo "${BinDir}/darknet detector test ${TrainData} ${TrainCfg} $Weights $img -gpus 0 -thresh $Thresh -out $out"
        # done < $validFile
    ;;
    *)
        echo "Error: Unknown command $1"
    ;;
esac